Rio config files updated to current rio version

diff --git a/bin/rio b/bin/rio
--- a/bin/rio
+++ b/bin/rio
@@ -106,13 +106,15 @@ groovyVersion=$(getVersion v.groovy)
 
 # Call the install script, do not assume that Groovy has been installed.
 installRioToLocalRepository() {
-    if [ -f "$RIO_LIB/groovy-all-$groovyVersion.jar" ]; then
-        groovyClasspath="-cp `toNative $RIO_LIB/groovy-all-$groovyVersion.jar`"
-        ""$JAVACMD"" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
-        $scriptDir/../configs/rio/install.groovy $JAVA_HOME $RIO_HOME
-    else
-        echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
-        exit 1
+    if [ ! -f "$RIO_HOME/logs/install.log" ]; then
+        if [ -f "$RIO_LIB/groovy-all-$groovyVersion.jar" ]; then
+            groovyClasspath="-cp `toNative $RIO_LIB/groovy-all-$groovyVersion.jar`"
+            ""$JAVACMD"" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
+            $scriptDir/../configs/rio/install.groovy $JAVA_HOME $RIO_HOME
+        else
+            echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
+            exit 1
+        fi
     fi
 }
 ##############################
